---
# tasks file for linux-server

- name: Load OS family variable
  debug:
    var: ansible_os_family

- name: 서비스 정보 수집 (Linux)
  service_facts:
  when: ansible_os_family == "RedHat"

- name: 서비스 정보 출력 (Redis만)
  debug:
    msg: "{{ services['redis'] if 'redis' in services else 'Redis 서비스가 없습니다.' }}"
  when: 
    - ansible_os_family == "RedHat"

- block:
    - name: 보안 설정 및 권한 관리
      become: yes
      import_tasks: ./Account_Security_Setting/redis_account_security.yml
    - name: 로그 활성화
      become: yes
      import_tasks: ./Patch_Log_Management/redis_Log.yml
  when: 
    - ansible_os_family == "RedHat"

