# 1. 모든 Windows 이벤트 로그를 가져오는 작업
- name: Get all Windows event logs using PowerShell
  win_shell: |
    $logs = @()
    foreach ($log in Get-EventLog -List) {
        $logName = $log.Log
        $events = Get-EventLog -LogName $logName -Newest 100 |
                  Select-Object -Property TimeGenerated, EntryType, Source, Message
        $logs += $events
    }
    # 이벤트 로그를 텍스트 형식으로 출력
    $logs | Format-Table -AutoSize | Out-String
  register: all_event_logs

- name: Debug output
  debug:
    var: all_event_logs.stdout

# 3. 이벤트 로그를 Ansible 경로에 파일로 저장
#- name: Save event logs to a file
 # copy:
  #  content: "{{ all_event_logs.stdout }}"
 #   dest: "/home/ubuntu/Master/windows/tasks/Patch_Log_Management/logs/all_log.txt"
#
