---
# 1. PowerShell을 사용하여 AutoAdminLogon 레지스트리 값을 확인
- name: Check if AutoAdminLogon exists and its value using PowerShell
  win_shell: |
    $key = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon"
    if (Test-Path $key) {
        $value = Get-ItemProperty -Path $key -Name AutoAdminLogon -ErrorAction SilentlyContinue
        if ($null -ne $value) {
            Write-Host "AutoAdminLogon value is: $($value.AutoAdminLogon)"
        } else {
            Write-Host "AutoAdminLogon does not exist."
        }
    } else {
        Write-Host "Registry path does not exist."
    }
  register: auto_admin_logon_output

# 3. AutoAdminLogon 값이 1일 때 취약 메시지 출력 (프로그램이 멈추지 않도록 설정)
- name: Fail if AutoAdminLogon is set to '1'
  fail:
    msg: "취약: AutoAdminLogon 값이 1로 설정되어 있습니다. AutoLogin 기능을 비활성화합니다."
  when: "'AutoAdminLogon value is: 1' in auto_admin_logon_output.stdout"
  ignore_errors: yes

# 4. PowerShell을 사용하여 AutoAdminLogon 값이 1이면 0으로 변경
- name: Set AutoAdminLogon to 0 if it is currently set to 1
  win_shell: |
    $key = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon"
    $value = Get-ItemProperty -Path $key -Name AutoAdminLogon -ErrorAction SilentlyContinue
    if ($null -ne $value -and $value.AutoAdminLogon -eq "1") {
        Set-ItemProperty -Path $key -Name AutoAdminLogon -Value "0"
        Write-Host "AutoAdminLogon was set to 1, now changed to 0."
    } else {
        Write-Host "No change needed."
    }
  when: "'AutoAdminLogon value is: 1' in auto_admin_logon_output.stdout"
  register: action_state

# 5. PowerShell을 사용하여 AutoAdminLogon 레지스트리 값을 다시 확인
- name: Check if AutoAdminLogon exists and its value after action
  win_shell: |
    $key = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon"
    if (Test-Path $key) {
        $value = Get-ItemProperty -Path $key -Name AutoAdminLogon -ErrorAction SilentlyContinue
        if ($null -ne $value) {
            Write-Host "AutoAdminLogon value is: $($value.AutoAdminLogon)"
        } else {
            Write-Host "AutoAdminLogon does not exist."
        }
    } else {
        Write-Host "Registry path does not exist."
    }
  register: auto_admin_logon_outputs

# 6. 레지스트리 값이 0으로 변경되었을 때 조치 완료 메시지 출력
- name: Display Debug action Complete Message for AutoAdminLogon
  debug:
    msg: "조치완료: AutoLogin 기능이 비활성화되었습니다."
  when: action_state is changed and auto_admin_logon_outputs.stdout | int == 0

# 7. AutoAdminLogon 값이 이미 0일 때 양호 메시지 출력
- name: Output Message System Check Results Good
  debug:
    msg: "양호: AutoLogin 기능이 비활성화 상태입니다."
  when: "'AutoAdminLogon value is: 0' in auto_admin_logon_output.stdout and action_state is not changed"
