---
- name: Check ShutdownWithoutLogon value in the registry
  ansible.windows.win_shell: |
    Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name ShutdownWithoutLogon | Select-Object -ExpandProperty ShutdownWithoutLogon
  register: shutdown_policy

# - name: Debug shutdown policy value
#   debug:
#     var: shutdown_policy.stdout

- name: Fail if ShutdownWithoutLogon is set to '1'
  fail:
    msg: "취약: 비로그인 상태에서 시스템 종료가 허용됩니다. 시스템 종료 비활성화 작업을 진행합니다."
  when: shutdown_policy.stdout | trim == '1'
  ignore_errors: yes

- name: Display message if ShutdownWithoutLogon is already disabled
  debug:
    msg: "양호: 비로그인 시스템 종료 기능이 비활성화 상태입니다."
  when: shutdown_policy.stdout | trim == '0'

- name: Ensure ShutdownWithoutLogon is set to '0' (disabled)
  ansible.windows.win_shell: |
    if ((Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System').ShutdownWithoutLogon -eq 1) {
      Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name ShutdownWithoutLogon -Value 0
      Write-Output "조치 완료: 비로그인 시스템 종료 기능이 비활성화 되었습니다."
    } else {
      Write-Output "양호: 비로그인 시스템 종료 기능이 비활성화 상태입니다."
    }
  when: shutdown_policy.stdout | trim == '1'
  register: change_shutdown_policy

- name: display message change shutdown policy is changed
  debug:
    msg: "조치 완료: 비로그인 시스템 종료 기능이 비활성화 되었습니다."
  when: change_shutdown_policy is changed
