---
- name: Check ShutdownWithoutLogon value in the registry
  ansible.windows.win_shell: |
    Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name ShutdownWithoutLogon | Select-Object -ExpandProperty ShutdownWithoutLogon
  register: shutdown_policy

- name: Display current ShutdownWithoutLogon value
  debug:
    msg: "ShutdownWithoutLogon value is {{ shutdown_policy.stdout }}."

- name: Ensure ShutdownWithoutLogon is set to '0' (disabled)
  ansible.windows.win_shell: |
    if ((Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System').ShutdownWithoutLogon -eq 1) {
      Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name ShutdownWithoutLogon -Value 0
      Write-Output "ShutdownWithoutLogon has been set to 0."
    } else {
      Write-Output "ShutdownWithoutLogon is already set to 0."
    }

- name: Confirm that ShutdownWithoutLogon has been set to '0'
  ansible.windows.win_shell: |
    Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name ShutdownWithoutLogon | Select-Object -ExpandProperty ShutdownWithoutLogon
  register: updated_shutdown_policy

- name: Display updated ShutdownWithoutLogon value
  debug:
    msg: "Updated ShutdownWithoutLogon value is {{ updated_shutdown_policy.stdout }}."

