---
# 1. secedit 명령어를 사용하여 cfg 파일로 보안 설정을 export
- name: Export security settings to cfg file
  win_command: secedit /export /cfg c:\cfg.txt
  args:
    chdir: C:\Windows\System32
  register: export_result

# 2. cfg.txt 파일에서 SeRemoteShutdownPrivilege 확인
- name: Read the exported cfg.txt file
  win_shell: type c:\cfg.txt
  register: cfg_content

# 3. SeRemoteShutdownPrivilege 값을 확인하고, 다른 사용자가 있다면 수정
- name: Ensure only Administrators have SeRemoteShutdownPrivilege
  win_shell: |
    (Get-Content c:\cfg.txt) -match 'SeRemoteShutdownPrivilege'
  register: privilege_check
# 4. privilege 권한 출력   
- name: Remove extra users from SeRemoteShutdownPrivilege if not only Administrators
  win_lineinfile:
    path: c:\cfg.txt
    regexp: '^SeRemoteShutdownPrivilege = .+'
    line: 'SeRemoteShutdownPrivilege = *S-1-5-32-544'
  when: "'S-1-5-32-544' not in privilege_check.stdout"

