---
- name: ssh key gen & deply
  hosts: localhost
  connection: local
  become: yes
  vars:
    - password: "dkagh1."
  tasks:
  - name: include service names
    include_vars:
      file: ./Linux-server/vars/ssh_key_deploy.yml

    
  - name: Generate SSH key
    shell: ssh-keygen -t rsa -b 4096 -f /home/semaphore/.ssh/id_rsa -N "" -y
    register: ssh_keygen_result
    ignore_errors: yes

  - name: ssh key check
    shell: cat /home/semaphore/.ssh/id_rsa
    register: private_key
    ignore_errors: yes

  - name: ssh key deploy
    expect:
      command: sudo ssh-copy-id -i /home/semaphore/.ssh/id_rsa.pub {{ item }}
      responses:
        "{{itme}}\'s password:" : "{{password}}"
    register: result
    loop: "{{user}}"
    ignore_errors: yes

  - name: ssh key check
    debug:
      msg: >
          private_key: {{ private_key}}
          {{result}}
          "complete"
  
