---
- name: ssh key gen & deply
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: include service names
    include_vars:
      file: ./Linux-server/vars/ssh_key_deploy.yml

    
  - name: ssh key gen
    expect:
      command: ssh-keygen -t rsa -b 4096 -f /home/semaphore/.ssh/id_rsa -N '' -y 
      responses:
        'Enter file in which to save the key': '\r'
        'Enter passphrase for key': '\r'
        'Enter same passphrase again': '\r'
      args:
        creates: /home/semaphore/.ssh/id_rsa
    ignore_errors: yes

  - name: ssh key check
    shell: cat /home/semaphore/.ssh/id_rsa
    register: private_key
    ignore_errors: yes

  - name: ssh key deploy
    shell: ssh-copy-id -i /home/semaphore/.ssh/id_rsa.pub {{ item }}
    register: result
    loop: "{{user}}"
    ignore_errors: yes

  - name: ssh key check
    debug:
      msg: >
          private_key: {{ private_key}}
          {{result}}
          "complete"
  
