---
- name: Enable intranet services
  hosts: mysql_test
  become: yes
  tasks:
    - name: 패스워드 복잡성 점검
      shell: cat /etc/security/pwquality.conf
      register: result
      ignore_errors: yes

    - name: enforce_for_root 설정 확인
      set_fact:
        enforce_root: "{{ item }}"
      loop: "{{ result.stdout_lines }}"
      when: "'enforce_for_root' in item"

    - name: retry 설정 확인
      set_fact:
        retry: "{{ item }}"
      loop: "{{ result.stdout_lines }}"
      when: "'retry' in item"

    - name: 패스워드 최소 길이 설정 확인
      set_fact:
        minlen: "{{ item }}"
      loop: "{{ result.stdout_lines }}"
      when: "'minlen' in item"

    - name: 패스워드 최소 숫자 갯수 설정 확인
      set_fact:
        dcredit: "{{ item }}"
      loop: "{{ result.stdout_lines }}"
      when: "'dcredit' in item"

    - name: 패스워드 최소 대문자 갯수 설정 확인
      set_fact:
        ucredit: "{{ item }}"
      loop: "{{ result.stdout_lines }}"
      when: "'ucredit' in item"

    - name: 패스워드 최소 소문자 갯수 설정 확인
      set_fact:
        lcredit: "{{ item }}"
      loop: "{{ result.stdout_lines }}"
      when: "'lcredit' in item"

    - name: 패스워드 최소 특수문자 갯수 설정 확인
      set_fact:
        ocredit: "{{ item }}"
      loop: "{{ result.stdout_lines }}"
      when: "'ocredit' in item"

    - name: 환경설정 파일 권한 확인
      debug:
        msg: >
          enforce_for_root: {{enforce_root}}
          retry 횟수: {{retry[-1]}}
          패스워드 최소길이: {{minlen[-1]}}
          패스워드 최소 숫자: {{ dcredit[-2]}}
          패스워드 최소 대문자: {{ ucredit[-2]}}
          패스워드 최소 소문자: {{ lcredit[-2]}}
          패스워드 최소 특수문자: {{ ocredit[-2]}}
          {{ '패스워드 복잡도가 적합합니다.' if (((minlen[-1] | int >= 8 and 
                                            ([(dcredit[-2:] | int < 0), (ucredit[-2:] | int < 0),
                                            (lcredit[-2:] | int < 0), (ocredit[-2:] | int < 0)] | select('equalto',true) | length >= 3 ))
                                            or 
                                            (minlen[-1] | int >= 10 and 
                                            ([(dcredit[-2:] | int < 0), (ucredit[-2:] | int < 0), 
                                            (lcredit[-2:] | int < 0), (ocredit[-2:] | int < 0)] | select('equalto',true) | length >= 2 ))) and 
                                            (enforce_root == 'enforce_for_root' and retry[-1] | int <= 3 )) else '패스워드 복잡도가 부적절합니다.'}}
