---
# tasks file for IIS

  #- name: Task for new_IIS_log.yml
  #  import_tasks: /home/ubuntu/Master/IIS/tasks/Security_Management/new_IIS_log.yml


- name: Return True If IIS Service is Running
  win_service:
    name: W3SVC
    state: started
  register: iis_service_state
  when: ansible_os_family == 'Windows'

- block:
  - name: Start for Cgi_Restrict.yml
    import_tasks: ./Security_Management/Cgi_Restrict.yml

  - name: Start for Webdav_off.yml
    import_tasks: ./Security_Management/Webdav_off.yml
  
  - name: Start for High_Directory_Access.yml
    import_tasks: ./Access_Management/High_Directory_Access.yml

  - name: Start for Link_Deny.yml
    import_tasks: ./Security_Management/Link_Deny.yml
  
  - name: Start for Unused_File_Delete.yml
    import_tasks: ./Security_Management/Unused_File_Delete.yml
  when: ansible_os_family == 'Windows' and iis_service.state == 'running'

- name: Skipping IIS Scan Logic
  debug:
    msg: "IIS Service가 발견되지 않아 검사 로직을 수행하지 않습니다."
  when: ansible_os_family != 'Windows' or iis_service.state != 'running'

- name: IIS Scan Logic is Done
  debug:
    msg: "IIS Service에 대한 점검 및 조치 로직을 수행하였습니다."
  when: ansible_os_family == 'Windows' and iis_service.state == 'running'