---
    - name: Install required packages for Ubuntu
      when: ansible_os_family == "Debian"
      apt:
        name:
          - wget
          - unzip
          - curl
        state: present

    - name: Install required packages for CentOS
      when: ansible_os_family == "RedHat"
      yum:
        name:
          - wget
          - unzip
          - curl
        state: present

    - name: Download Promtail binary for Ubuntu
      when: ansible_os_family == "Debian"
      get_url:
        url: https://github.com/grafana/loki/releases/download/v2.8.1/promtail-linux-amd64.zip
        dest: /tmp/promtail-linux-amd64.zip

    - name: Download Promtail binary for CentOS
      when: ansible_os_family == "RedHat"
      get_url:
        url: https://github.com/grafana/loki/releases/download/v2.8.1/promtail-linux-amd64.zip
        dest: /tmp/promtail-linux-amd64.zip

    - name: Unzip Promtail binary
      unarchive:
        src: /tmp/promtail-linux-amd64.zip
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'
    
    - name: Rename the Promtail binary
      command: mv /usr/local/bin/promtail-linux-amd64 /usr/local/bin/promtail

    - name: Create Promtail configuration directory
      file:
        path: /etc/promtail
        state: directory

    - name: Create Promtail position file
      copy:
        dest: /var/log/promtail-position.yaml
        content: |
          
    - name: Create Promtail configuration file
      copy:
        dest: /etc/promtail/config.yml
        content: |
          server:
            http_listen_port: 9080
            grpc_listen_port: 9095

          positions:
            filename: /var/log/promtail-position.yaml

          clients:
            - url: http://192.168.56.101:3100/loki/api/v1/push  # Loki 서버 IP 주소
          scrape_configs:
            - job_name: hawkey
              static_configs:
                - targets:
                    - localhost
                  labels:
                    job: hawkey
                    ip_address: 10.0.2.6
                    __path__: /var/log/hawkey.log
                 
            - job_name: btmp
              static_configs:
                - targets:
                    - localhost
                  labels:        
                    job: btmp
                    ip_address: 10.0.2.6
                    __path__: /var/log/btmp    
            
            - job_name: secure
              static_configs:
                - targets:
                    - localhost
                  labels:
                    job: secure
                    ip_address: 10.0.2.6
                    __path__: /var/log/secure

            - job_name: messages
              static_configs:
                - targets:
                    - localhost
                  labels:
                    job: messages
                    ip_address: 10.0.2.6
                    __path__: /var/log/messages


    - name: Create Promtail systemd service file
      copy:
        dest: /etc/systemd/system/promtail.service
        content: |
          [Unit]
          Description=Promtail service
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/promtail -config.file=/etc/promtail/config.yml
          Restart=always

          [Install]
          WantedBy=multi-user.target
    
    - name: Start and enable Promtail service
      systemd:
        name: promtail
        state: started
        enabled: yes

