---
  - name: 서비스 이름 포함
    include_vars:
      file: ../vars/vulnerablity_rtype_services.yml
  
  - name: Finger 서비스 존재 여부 확인
    stat:
      path: /etc/xinet.d
    register: stat_status
  
  - name: 존재 여부 확인
    debug:
      msg: "양호: inetd 폴더가 존재하지 않습니다."
    when: not stat_status.stat.exists
  
  - name: Finger 서비스 상태 확인
    systemd:
      name: finger
      state: started
    register: service_status
    failed_when: service_status is defined
    ignore_errors: yes
  
  - name: Finger 서비스가 존재하지 않을 경우 실패
    fail:
      msg: "취약: Finger 서비스 활성화"
    when: service_status is succeeded
  
  - name: rTypeFile 존재 여부 확인
    stat:
      path: "/etc/xinet.d/{{ item }}"
    register: rtype_stat_status
    loop: "{{ check_services }}"
  
  - name: rTypeFile이 존재할 경우 서비스 파일 수정
    lineinfile:
      path: "/etc/xinet.d/{{ item }}"
      regexp: '^disable'
      line: 'disable = yes'
    when: item in rtype_stat_status and rtype_stat_status[item].stat.exists
    loop: "{{ check_services }}"
  
  
