- name: Check IIS version
  win_shell: |
    $iisVersion = (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\InetStp").VersionString
    if ($iisVersion) {
        # 숫자 부분만 추출하여 float로 변환
        $versionNumber = [float]$iisVersion.Split(' ')[1]
        Write-Output $versionNumber
       # if ($versionNumber -ge 7.0) {
       #     Write-Output "$versionNumber"
       # } else {
       #     Write-Output "$versionNumber"
       # }
    } 
    else {
        Write-Output "IIS is not installed."
    }
  register: iis_version

- name: Stdout Version
  debug:
    msg: >
      {{'현재' if (iis_version.stdout | float >= 7.0)}}
      IIS Version : {{iis_version.stdout}}"

- name: Define virtual directories to check
  set_fact:
    virtual_directories:
      - "C:\\inetpub\\iissamples"
      - "C:\\winnt\\help\\iishelp"
      - "C:\\Program Files\\Common Files\\System\\MSADC\\Sample"
  when: iis_version.stdout | float < 7.0

- name: Check virtual directories if they exist
  win_shell: |
    $dirPath = "{{dirPath}}"
    if (Test-Path $dirPath) {
        Write-Output "Exist: $dirPath"
    } else {
        Write-Output "Not found: $dirPath"
    }
  loop: "{{ virtual_directories }}"
  loop_control:
    loop_var: dirPath
  when: iis_version.stdout | float < 7.0  
  register: directory_check_results

- name: Check
  debug:
    msg: >
      {{ '양호: 가상디렉터리가 존재하지 않습니다.' if 'Exits' not in directory_check_results else '취약: 가상디렉터리가 존재합니다.' }}
      IIS Version : {{ iis_version.stdout }}

