---
# 1. IIS 서비스 사용 여부 확인 (W3SVC 서비스 상태 확인)
- name: Check if IIS (W3SVC) service is running using PowerShell
  win_shell: |
    $service = Get-Service -Name W3SVC
    if ($service.Status -eq 'Running') {
        Write-Output "Running"
    } else {
        Write-Output "not Running"
    }
  register: iis_service_status

# 2. 레지스트리의 DisableWebDAV 값 출력 및 값 수정
- name: Get DisableWebDAV value from the registry using PowerShell
  win_shell: |
    $regPath = 'HKLM:\SYSTEM\CurrentControlSet\Services\W3SVC\Parameters'
    $regName = 'DisableWebDAV'
    $regValue = Get-ItemProperty -Path $regPath -Name $regName | Select-Object -ExpandProperty $regName
    Write-Output $regValue
  register: webdav_reg_value

- name: Set DisableWebDAV to 1 if not already set using PowerShell
  win_shell: |
    $regPath = 'HKLM:\SYSTEM\CurrentControlSet\Services\W3SVC\Parameters'
    $regName = 'DisableWebDAV'
    $currentValue = "{{ webdav_reg_value.stdout }}"
    if ($currentValue -ne 1) {
        Set-ItemProperty -Path $regPath -Name $regName -Value 1
        Write-Output "DisableWebDAV value set to 1"
    } else {
        Write-Output "DisableWebDAV value is already 1"
    }
  register: set_webdav_result

- name: Output DisableWeb value modification result
  debug:
    msg: "{{ set_webdav_result.stdout }}"

- name: Output IIS service status
  debug:
    msg: |
      {{'양호: webdav 설정이 적절합니다.' if (iis_service_status.stdout == 'not Running' and webdav_reg_value.stdout | int == 1) 
      else '취약: webdev 설정이 부적절합니다.'}}
      IIS Service is {{ iis_service_status.stdout }}
      Current DisableWebDAV value is {{ webdav_reg_value.stdout }}

