---
  - name: 패스워드 최대 사용 기간 점검
    shell: cat /etc/login.defs
    register: result
    ignore_errors: yes
  
  - name: 패스워드 최대 사용 기간 설정
    lineinfile:
      path: /etc/login.defs
      regexp: '^PASS_MAX_DAYS'
      line: 'PASS_MAX_DAYS  90'
  
  - name: 설정완료
    debug:
      msg: "set complete"
    
