---

- name: File Check Apache Config
  stat:
    path: /etc/httpd/conf/httpd.conf
  register: http_state
  ignore_errors: yes

# 디렉터리 리스팅 기능이 활성화되어 있는지 확인
- name: Check if Directory Listing is Enabled
  shell: grep '^\s*Options\s\+.*Indexes.*' /etc/httpd/conf/httpd.conf
  register: directory_listing_status
  when: http_state.stat.exists
  ignore_errors: yes
  changed_when: false

# 디렉터리 검색 기능이 비활성화되어 양호한 상태인 경우
- name: Debug message when directory listing is off
  debug:
    msg: "양호: 디렉터리 검색 기능이 사용되지 않고 있습니다."
  when: directory_listing_status.stdout is not defined or directory_listing_status.stdout == ""

# 디렉터리 검색 기능이 활성화되어 취약한 경우 - 경고 메시지 출력
- name: Warn if directory listing is on
  fail:
    msg: "취약: 디렉터리 검색 기능이 활성화되어 있습니다. 환경 설정 파일에서 'Indexes'를 제거하는 작업을 진행합니다."
  when: directory_listing_status.stdout is defined and directory_listing_status.stdout != ""
  ignore_errors: yes

# 디렉터리 검색 기능 제거 (옵션에서 Indexes 삭제)
- name: Remove Indexes from Directory Options
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^(Options\s+)(Indexes)?(.*)$'
    line: '\1\3'
    backrefs: yes
  when: directory_listing_status.stdout is defined and directory_listing_status.stdout != ""
  ignore_errors: yes

# 조치가 완료되었음을 출력
- name: Debug message after fixing directory listing
  debug:
    msg: "조치 완료: 'Indexes' 옵션이 제거되었습니다. 디렉터리 검색 기능이 더 이상 활성화되지 않습니다."
  when: directory_listing_status.stdout is defined and directory_listing_status.stdout != ""


# Get Every apache와 관련된 모든Process List
- name: Search Apache Deamon
  command: ps -ef | grep apache2
  register: apache_process
  changed_when: false
  ignore_errors: yes

- name: Check if Any Apache Process is Running by Root
  shell: ps -eo user,comm | grep '[a]pache' | grep '^root' | wc -l
  register: apache_runningby_root
  changed_when: false
  ignore_errors: yes

- name: Warn to User Apache Service Running By Root
  fail:
    msg: "취약: 데몬이 root권한으로 구동되고 있습니다.  APACHE_RUN_USER, APACHE_RUN_GROUP을 별도의 계정으로 변경해주세요."
  when: apache_runningby_root.stdout | int > 0
  ignore_errors: yes

- name: User Apache Service is not Running By Root
  debug:
    msg: "양호: Apache가 root 권한으로 실행되지 않고 있습니다."
  when: apache_runningby_root.stdout | int == 0