---
    # 로그 활성화 (조치 X)
  - name: Get Redis Slowing Configuration
    command: redis-cli config get slowing-log-slower-than
    register: slowlog_config
    ignore_errors: yes

  - name: Extract the Number Value
    set_fact:
      slowlog_value: "{{ slowlog_config.stdout | regex_search('\\d+') }}"

  - name: Check if The slowlog value is negative
    command: redis-cli config set slowing-log-slower-than 100
    when: slowlog_value | int < 0


  # 디버그 메시지 출력
  - name: slowlog 설정 및 loglevel 확인
    debug:
      msg: >
        {% if slowlog_value | int == 100 and loglevel_check.rc == 0 %}
        "양호: 'slowlog-log-slower-than' 값이 100이고 'loglevel'이 notice로 설정되어 있습니다."
        {% else %}
        "취약: 'slowlog-log-slower-than' 값이 10000이거나 'loglevel'이 notice로 설정되어 있지 않습니다."
        {% endif %}
    when: true  # 항상 실행

