---

  - name: general_log 활성화 점검
    mysql_query:
      login_user: root
      query: "show VARIABLES like 'general_log%'; "
    register: result1
    ignore_errors: yes
  
  - name: slow_log 활성화 점검
    mysql_query:
      login_user: root
      query: "show VARIABLES like 'slow%'; "
    register: result2
    ignore_errors: yes

  - name: general_log 활성화
    mysql_query:
      login_user: root
      query: "set global general_log = 'ON';"
    when: "result1.query_result[0][0].Value == 'OFF' and result2.query_result[0][1].Value == 'OFF'"
    ignore_errors: yes

  - name: slow_log 활성화
    mysql_query:
      login_user: root
      query: "set global slow_query_log = 'ON';"
    when: "result1.query_result[0][0].Value == 'OFF' and result2.query_result[0][1].Value == 'OFF'"
    ignore_errors: yes



