---
  - name: 패스워드 복잡도 설정  점검
    mysql_query:
      login_user: root
      query: "show VARIABLES like 'validate_password%'; "
    register: result
    ignore_errors: yes

  - name: 패스워드 정책 추출
    set_fact:
      password_policy: "{{ item.Value }}"
    loop: "{{ result.query_result[0] }}"
    when: item.Variable_name == 'validate_password.policy'
  
  - name: 패스워드 정책 적용 
    mysql_query:
      login_user: root
      query: "set global validate_password.policy=MEDIUM;"
    when: password_policy == 'LOW'

  - name: 패스워드 정책 업데이트
    set_fact:
      password_policy: "MEDIUM"
    when: password_policy == 'LOW'

  - name: 패스워드 길이 확인
    set_fact:
      password_length: "{{ item.Value }}"
    loop: "{{ result.query_result[0] }}"
    when: item.Variable_name == 'validate_password.length'
  
  - name: 패스워드 길이 값 적용
    mysql_query:
      login_user: root
      query: "set global validate_password.length=8;"
    when: password_length | int < 8

  - name: 패스워드 길이 없데이트
    set_fact:
      password_length: 8
    when: password_length | int < 8

  - name: 패스워드 복잡도 조건 확인
    set_fact:
      mixed_case_count: "{{ item.Value }}"
    loop: "{{ result.query_result[0] }}"
    when: item.Variable_name == 'validate_password.mixed_case_count'
    
  - name: 패스워드 복잡도 적용
    mysql_query:
      login_user: root
      query: "set global validate_password.mixed_case_count=1;"
    when: mixed_case_count | int < 1

  - name: 패스워드 복잡도 조건 업데이트
    set_fact:
      mixed_case_count: 1
    when: mixed_case_count | int < 1

  - name: 패스워드 특수문자 조건 확인
    set_fact:
      special_char_count: "{{ item.Value }}"
    loop: "{{ result.query_result[0] }}"
    when: item.Variable_name == 'validate_password.special_char_count'

  - name: 패스워드 특수문자 조건 적용
    mysql_query:
      login_user: root
      query: "set global validate_password.special_char_count=1;"
    when: special_char_count | int < 1
  
  - name: 패스워드 특수문자 조건 업데이트
    set_fact:
      special_char_count: 1
    when: special_char_count | int < 1
  
  - name: 패스워드 숫자 조건 확인
    set_fact:
      number_count: "{{ item.Value }}"
    loop: "{{ result.query_result[0] }}"
    when: item.Variable_name == 'validate_password.number_count'

  - name: 패스워드 숫자 조건 적용
    mysql_query:
      login_user: root
      query: "set global validate_password.number_count=1;"
    when: number_count | int < 1

  - name: 패스워드 숫자 조건 확인
    set_fact:
      number_count: 1
    when: number_count | int < 1

  - name: 패스워드 정책 및 길이 적합성 점검
    debug:
      msg: >
        Password policy: {{ password_policy }},
        Password length: {{ password_length }},
        Mixed case count: {{ mixed_case_count }},
        Special character count: {{ special_char_count }},
        Number count: {{ number_count }}
        {{ '패스워드 복잡도가 적합합니다.' if ((password_policy == 'MEDIUM' or password_policy == 'STRONG')  and password_length | int >= 8 and mixed_case_count | int >= 1 and special_char_count | int >= 1 and number_count | int >= 1) else '패스워드 복잡도가 불충분합니다.' }}

