---
  - name: root 권한 실행 점검
    shell: cat /etc/my.cnf.d/mysql-server.cnf
    register: result
    ignore_errors: yes

  - name: 실행 user 정보 확인
    set_fact:
      current_user_info: "{{ item }}"
    loop: "{{ result.stdout_lines }}"
    when: "'#' not in item and 'user' in item"
  
  - name: 실행 user mysql로 변경
    lineinfile:
      path: /etc/my.cnf.d/mysql-server.cnf
      regexp: '{{current_user_info}}'
      line: "user = mysql"
    when: "'root' in current_user_info"

  - name: 현재 실행 user 정보
    debug:
      msg: "현재 실행 user 정보 : {{ current_user_info if 'root' not in current_user_info else 'user = mysql'}}"

