- name: Master Playbook for System Management
  hosts: linux
  become: yes
  gather_facts: yes


  roles:
    # Include the role for Redis server management
    - role: Redis
    # Include the role for Linux server management
    - role: Linux-server
    # Include the role for MySQL server management
    - role: MySQL
    # Include the role for Redis server management
    #- role: Redis
    # Include the role for Apache server management
    - role: Apache
  
  #tasks:
   # - name: 
