---
  
  - name: 윈도우 검사 및 조치 로직 시작
    block:
    - name: Start tasks from Save_log.yml
      import_tasks: ./Patch_Log_Management/Save_Log.yml
    
    - name: Start tasks from Account_Management/Pwd_period_Check.yml
      import_tasks: ./Account_Management/Pwd_period_Check.yml
    
    - name: Start tasks from Account_Management/Account_Management/Id_Locked_Check.yml
      import_tasks: ./Account_Management/Id_Locked_Check.yml
    
    - name: Start tasks from Unused_Service_Check.yml
      import_tasks: ./Service_Management/Unused_Service_Check.yml
    
    - name: Start tasks from Anonymous_Ftp_Forbid.yml
      import_tasks: ./Service_Management/Anonymous_Ftp_Forbid.yml
    
    - name: Start tasks from Servicepack_Check.yml
      import_tasks: ./Patch_Log_Management/Servicepack_Check.yml

    - name: Start tasks from Remote_Registry_Check.yml
      import_tasks: ./Patch_Log_Management/Remote_Registry_Check.yml

    - name: Start tasks from Notlogin_Systemoff.yml
      import_tasks: ./Security_Management/Notlogin_Systemoff.yml

    - name: Start tasks from Systemoff_by_Remote.yml
      import_tasks: ./Security_Management/Systemoff_by_Remote.yml

    - name: Start tasks from Autologin_control.yml
      import_tasks: ./Security_Management/Autologin_control.yml
    when: ansible_os_family == 'Windows'

  - name: Skipping Windows scan Logic
    debug:
      msg: "검사 대상이 Windows 운영체제가 아니기 때문에 검사가 수행되지 않습니다."
    when: ansible_os_family != 'Windows'
  
  - name: Windows Inspect is Done
    debug:
      msg: "Windows 시스템에 대한 검사 및 조치가 수행되었습니다."
    when: ansible_os_family == 'Windows'
  