- name: Check and modify IIS applicationHost.config settings
  win_shell: |
    $configPath = "{{ application_host_config }}"
    [xml]$config = Get-Content $configPath

    $notListedIsapisAllowed = $config.configuration.'system.webserver'.security.isapiCgiRestriction.notListedIsapisAllowed
    $notListedCgisAllowed = $config.configuration.'system.webserver'.security.isapiCgiRestriction.notListedCgisAllowed

    $results = @()

    if (-not $notListedIsapisAllowed -or $notListedIsapisAllowed -eq "false") {
        $results += "notListedIsapisAllowed is not set or is false. (양호)"
    } else {
        $results += "notListedIsapisAllowed is set to true. (수정 필요)"
        $config.configuration.'system.webServer'.security.isapiCgiRestriction.notListedIsapisAllowed = "false"
    }

    if (-not $notListedCgisAllowed -or $notListedCgisAllowed -eq "false") {
        $results += "notListedCgisAllowed is not set or is false. (양호)"
    } else {
        $results += "notListedCgisAllowed is set to true. (수정 필요)"
        $config.configuration.'system.webServer'.security.isapiCgiRestriction.notListedCgisAllowed = "false"
    }

    # 변경된 내용을 파일에 저장
    $config.Save($configPath)

    # 결과 반환
    $results -join "`n"
  register: check_results

- name: Print results
  debug:
    var: check_results.stdout_lines

#### 3. 조치 이후 결과값 다시 출력
- name: Changed Value
  win_shell: |
    $configPath = "{{ application_host_config }}"
    [xml]$config = Get-Content $configPath

    $notListedIsapisAllowed = $config.configuration.'system.webserver'.security.isapiCgiRestriction.notListedIsapisAllowed
    $notListedCgisAllowed = $config.configuration.'system.webserver'.security.isapiCgiRestriction.notListedCgisAllowed

    $results = @()

    if (-not $notListedIsapisAllowed -or $notListedIsapisAllowed -eq "false") {
        $results += "notListedIsapisAllowed is not set or is false. (양호)"
    } else {
        $results += "notListedIsapisAllowed is set to true. (수정 필요)"
    }

    if (-not $notListedCgisAllowed -or $notListedCgisAllowed -eq "false") {
        $results += "notListedCgisAllowed is not set or is false. (양호)"
    } else {
        $results += "notListedCgisAllowed is set to true. (수정 필요)"
    }

    # 결과 반환
    $results -join "`n"
  register: check_results

- name: Print results
  debug:
    var: check_results.stdout_lines

