---
- name: Check and modify IIS applicationHost.config settings
  win_shell: |
    $configPath = "{{ application_host_config }}"
    [xml]$config = Get-Content $configPath

    $notListedIsapisAllowed = $config.configuration.'system.webserver'.security.isapiCgiRestriction.notListedIsapisAllowed
    $notListedCgisAllowed = $config.configuration.'system.webserver'.security.isapiCgiRestriction.notListedCgisAllowed

    $results = @()

    if ( $notListedIsapisAllowed -or $notListedIsapisAllowed -eq "false") {
        $config.configuration.'system.webServer'.security.isapiCgiRestriction.notListedIsapisAllowed = "false"
    } 

    if ( $notListedCgisAllowed -or $notListedCgisAllowed -eq "false") {
        $config.configuration.'system.webServer'.security.isapiCgiRestriction.notListedCgisAllowed = "false"
    }

    # 변경된 내용을 파일에 저장
    $config.Save($configPath)

  register: check_results

- name: Print results
  debug:
    var: check_results.stdout_lines


