---
# tasks file for linux-server

- name: debug print
  debug:
    msg: "test"

- name: Security settings and permissions management
  import_tasks: /Account_Security_Setting/redis_account_security.yml

- name: Enabling Logs
  import_tasks: /Account_Security_Setting/redis_Log
