---
# 1. net accounts 명령을 실행하여 계정 잠금 임계값 확인
- name: Check account lockout threshold using net accounts
  win_shell: |
    net accounts
  register: account_lockout_output

# 2. 현재 잠금 임계값 디버그 메시지 출력
- name: Display current lockout threshold
  debug:
    msg: "{{ account_lockout_output.stdout_lines }}"
  
# 3. 잠금 임계값이 never 혹은 5 초과일 경우 5로 설정
- name: Set lockout threshold to 5 if it is never or more than 5
  win_shell: |
    net accounts /lockoutthreshold:5
  when: "'Lockout threshold' in account_lockout_output.stdout and ('Never' in account_lockout_output.stdout or (account_lockout_output.stdout | regex_search('Lockout threshold *: *([0-9]+)') | int > 5))"
  register: lockout_threshold_change

# 4. 변경 후 디버그 메시지 출력
- name: Display lockout threshold change message
  debug:
    msg: "Lockout threshold was set to 5."
  when: lockout_threshold_change.changed

