---
- name: Fetch all active users and check password expiration
  win_command: |
    wmic useraccount where "Disabled=FALSE" get Name, PasswordExpires
  register: active_users

- name: Display active users and their password expiration status
  debug:
    var: active_users.stdout_lines

- name: Set password expiration for users with no expiration set
  win_command: |
    wmic useraccount where "Name='{{ item }}' and PasswordExpires=FALSE" set PasswordExpires=TRUE
  loop: "{{ active_users.stdout_lines | select('search', 'FALSE') | map('regex_replace', '\\s+.*$', '') | list }}"
  when: item != "Name"

- name: Ensure maximum password age is set to 90 days
  win_command: |
    net accounts /MAXPWAGE:90

