---
  - name: Get Stickybit File List
    command: find / -user root -type f \( -perm -4000 -o -perm -2000 \) -exec ls -lg {} \;
    register: stickybit_file_list
    ignore_errors: yes
    changed_when: false
  
  - name: Display Security Status of Sticky Bit Files
    debug:
      msg: >
        {% if stickybit_file_list.stdout_lines | length > 0 %}
          "취약: 주요 실행파일의 권한에 SUID 또는 SGID가 설정되어 있습니다:\n{{ stickybit_file_list.stdout_lines | join('\n') }}"
        {% else %}
          "양호: 주요 실행파일의 권한에 SUID 및 SGID 설정이 부여되어 있지 않습>니다."
        {% endif %}
    when: stickybit_file_list is defined