---

  - name: 환경설정 파일 권한 점검
    shell: ls -alL /etc/my.cnf.d/mysql-server.cnf
    register: result
    ignore_errors: yes

  - name: 환경설정 파일 권한 조치
    shell: chmod 640 /etc/my.cnf.d/mysql-server.cnf
    ignore_errors: yes


