---
# main.yml: Execute the Apache configuration checks and tasks

- hosts: web
  become: yes
  tasks:
    - name: Execute web service separation task
      import_tasks: /home/devops/project/access_control/process_directory.yml

    - name: Execute limit upload and download size task
      import_tasks: /home/devops/project/secruity/limit_upload_download.yml

    - name: Execute web service separation for DocumentRoot task
      import_tasks: /home/devops/project/secruity/web_service_separation.yml
