---
# tasks/main.yml

- name: Get the list of FTP sites
  ansible.windows.win_shell: |
    Import-Module WebAdministration
    Get-WebSite | Where-Object { $_.Name -like '*FTP*' } | Select-Object -ExpandProperty name
  register: ftp_sites

- name: Check if anonymous FTP is enabled for each site
  ansible.windows.win_shell: |
    Import-Module WebAdministration
    $enabled = Get-WebConfigurationProperty -Filter "system.ftpServer/security/authentication/anonymousAuthentication" -PSPath "IIS:\\Sites\\{{ item }}" -Name "enabled"
    if ($enabled -eq $null) {
      Write-Host "Not Configured"
    } else {
      Write-Host $enabled
    }
  register: ftp_auth_status
  loop: "{{ ftp_sites.stdout_lines }}"
  ignore_errors: yes

- name: Output FTP auth status
  debug:
    msg: >
      {% if ftp_auth_status.results %}
        {% for result in ftp_auth_status.results %}
          Site: {{ ftp_sites.stdout_lines[loop.index0] }} - 
          Status: {{ result.stdout | default('Not Configured') }}
        {% endfor %}
      {% else %}
        No FTP sites found.
      {% endif %}

