---
- name: Check if Remote Registry Service is running
  ansible.windows.win_command: "net start"
  register: net_start_output

- name: Display running services
  debug:
    var: net_start_output.stdout_lines

- name: Check if Remote Registry Service is running
  set_fact:
    remote_registry_running: "{{ 'Remote Registry' in net_start_output.stdout }}"

- name: Stop Remote Registry Service if it is running
  ansible.windows.win_service:
    name: RemoteRegistry
    state: stopped
  when: remote_registry_running

