--- 
# tasks file for linux-server
- name: Load OS family variable
  debug:
    var: ansible_os_family

- name: Service check
  debug:
    msg: "OS가 Redhat이 아니므로 검사를 건너뜁니다."
  when: ansible_os_family != "RedHat" and ansible_os_family != "Rocky"

- name: 서비스 정보 수집 (Linux)
  service_facts:
  when: ansible_os_family == "RedHat" or ansible_os_family != "Rocky"

- block:
  
  - name: Include FileList
    include_vars: ../vars/file_check_list.yml
  - name: Include Vunerability Services List
    include_vars: ../vars/vulnerablity_rtype_services.yml

  - name: Remote access restrictions
    import_tasks: ./Account_Managment/server_account.yml
  
  - name: Configuring Complexity
    import_tasks: ./Account_Managment/server_password.yml
  
  - name: Setting thresholds
    import_tasks: ./Account_Managment/server_threshold.yml
  
  - name: Set the maximum usage period
    import_tasks: ./Account_Managment/server_password_max.yml
  
  - name: Protection
    import_tasks: ./Account_Managment/server_password_protect.yml
  
  - name: file directory
    import_tasks: ./File_Directory_ManageMent/FileDirectory.yml
  
  - name: StickbitCheck
    import_tasks: ./File_Directory_ManageMent/StickbitCheck.yml
  
  - name: Inspect Finger Vulnerability
    import_tasks: ./System_Management/ServiceFinger.yml
  
  - name: Inspect FTP Service Vulnerability
    import_tasks: ./System_Management/FTP.yml
  
  - name: Inspect NFS Service Vulnerability
    import_tasks: ./System_Management/NFS.yml
  
  - name: Inspect AutoMountd Vulnerability
    import_tasks: ./System_Management/automountd.yml
  
  - name: Inspect DNS Vulnerability
    import_tasks: ./System_Management/DNS.yml
  
  - name: Inspect Sendmail Vulnerability
    import_tasks: ./System_Management/Sendmail.yml
  
  when: ansible_os_family == "RedHat" or ansible_os_family != "Rocky"

